### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by prabhudev797** [DeviPrasadKL/SomeInformation#4]
Hello Devi,

No doubt you are doing a great job. However, I noticed that in your recent update you have introduced SocketIO. I personally feel that the update is incomplete. You have provided the client side implementation of Socket however, it would be great if you could update the server side detail about the same.

Hoping you will update it soon. Thank you.

**Comment by DeviPrasadKL** [comment]
Hello Prabhu,

I have added two files in the socket.io folder: one is `frappe_server.js`, which demonstrates how to connect a socket in the Frappe environment, and the other is `pure_server.js`, which shows how to set up a regular socket connection in Node.js.

I hope this helps!
